ServiceHost/Areas/Admin/Controllers/BannerController.cs
using AdminManagement.Application.Contract.BannerAgg;
using AdminManagement.Infrastructure.Configuration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServiceHost.Tools;
using StoreManagement.Application.Contract.StoreAgg;
using System.Threading.Tasks;

namespace ServiceHost.Areas.Admin.Controllers
{
    [AdminPermissionChecker(AdminPermissionHelper.Banners)]
    public class BannerController : AdminBaseController
    {
        private readonly IStoreApplication _storeApplication;
        private readonly IBannerApplication _bannerApplication;

        public BannerController(IStoreApplication storeApplication, IBannerApplication bannerApplication)
        {
            _storeApplication = storeApplication;
            _bannerApplication = bannerApplication;
        }

        public async Task<IActionResult> Index() => View(await _bannerApplication.GetAll());

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBannerVM command)
        {
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            var result = await _bannerApplication.Create(command);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            return PartialView(await _bannerApplication.GetDetailForEditBy(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBannerVM command)
        {
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            var result = await _bannerApplication.Edit(command);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }

        [HttpGet]
        public async Task<IActionResult> ChangeStatus(long id)
        {
            var result = await _bannerApplication.ActiveOrDeActive(id);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;
            else TempData[ErrorMessage] = result.Message;

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(long id) => PartialView(id);

        [ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(long id)
        {
            var result = await _bannerApplication.Delete(id);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Admin/Views/Banner/Create.cshtml
@model AdminManagement.Application.Contract.BannerAgg.CreateBannerVM


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد بنر جدید</h4>
</div>

<form asp-area="Admin" asp-controller="Banner" asp-action="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="StoreId" class="control-label">شرکت</label>
                    <select class="form-control" asp-for="StoreId" asp-items="@ViewBag.Stores">
                        <option value="0">انتخاب کنید...</option>
                    </select>
                    <span asp-validation-for="StoreId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictuerAlt" class="control-label">تصویر جایگزین</label>
                    <input type="text" class="form-control" asp-for="PictuerAlt">
                    <span asp-validation-for="PictuerAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان تصویر</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Position" class="control-label">موقعیت</label>
                    <select asp-for="Position" class="form-control">
                        <option value="0"> سطر اول </option>
                    </select>
                    <span asp-validation-for="Position" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ColSize" class="control-label">اندازه</label>
                    <input type="text" class="form-control" asp-for="ColSize">
                    <span asp-validation-for="ColSize" class="error"></span>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Url" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Url">
                    <span asp-validation-for="Url" class="error"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/Banner/Delete.cshtml
@model long

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">حذف</h4>
</div>

<form asp-area="Admin" asp-controller="Banner" asp-action="Delete"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <h5 style="font-style: oblique">آیا از حذف این موجودیت اطمینان دارید؟</h5>
    </div>
    <div class="modal-footer">
        <input name="id" asp-for="@Model" type="hidden" />
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">خیر</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">بله</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/Banner/Edit.cshtml
@model AdminManagement.Application.Contract.BannerAgg.EditBannerVM


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش بنر </h4>
</div>

<form asp-area="Admin" asp-controller="Banner" asp-action="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="StoreId" class="control-label">شرکت</label>
                    <select class="form-control" asp-for="StoreId" asp-items="@ViewBag.Stores">
                        <option value="0">انتخاب کنید...</option>
                    </select>
                    <span asp-validation-for="StoreId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictuerAlt" class="control-label">تصویر جایگزین</label>
                    <input type="text" class="form-control" asp-for="PictuerAlt">
                    <span asp-validation-for="PictuerAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان تصویر</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Position" class="control-label">موقعیت</label>
                    <select asp-for="Position" class="form-control">
                        <option value="0"> سطر اول </option>
                    </select>
                    <span asp-validation-for="Position" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ColSize" class="control-label">اندازه</label>
                    <input type="text" class="form-control" asp-for="ColSize">
                    <span asp-validation-for="ColSize" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Url" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Url">
                    <span asp-validation-for="Url" class="error"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="PictureName" />
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/Banner/Index.cshtml
@using Framework.Application
@model IEnumerable<AdminManagement.Application.Contract.BannerAgg.BannerVM>
@{
    ViewData["Title"] = "بنر ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Action("Create","Banner")"><i class="fa fa-plus"></i></a>
        </p>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@ViewData["Title"]</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 makeTableResponsive">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>شرکت</th>
                                    <th>تصویر</th>
                                    <th>اندازه</th>
                                    <th>موقعیت</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>تاریخ بروزرسانی</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                @foreach (var entity in Model)
                                {
                                    <tr>
                                        <td>@entity.Id</td>
                                        <td>@entity.StoreName</td>
                                        <td>
                                            <img style="width: 15%; border-radius: 15%" src="/Pictures/@entity.Picture" />
                                        </td>
                                        <td>@entity.ColSize</td>
                                        <td>@entity.Position.GetEnumName()</td>
                                        <td>
                                            @if (entity.IsActive)
                                            {
                                                <span class="text-success"><i class="glyphicon glyphicon-ok"></i></span>
                                            }
                                            else
                                            {
                                                <span class="text-danger"><i class="fa fa-close"></i></span>
                                            }
                                        </td>

                                        <td>@entity.CreatedDate</td>
                                        <td>@entity.LastUpdatedDate</td>
                                        <td>

                                            <a class="btn @((entity.IsActive)? "btn-danger" : "btn-success") pull-right m-rl-5"
                                               asp-action="ChangeStatus" asp-route-id="@entity.Id">
                                                <i class="fa @((entity.IsActive)? "fa-thumbs-down" : "fa-thumbs-up")"></i>
                                            </a>

                                            <a class="btn btn-warning pull-right m-rl-5"
                                               href="#showmodal=@Url.Action("Edit", "Banner", new {id = entity.Id})">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <a class="btn btn-danger pull-right m-rl-5"
                                               href="#showmodal=@Url.Action("Delete", "Banner", new {id = entity.Id})">
                                                <i class="fa fa-trash"></i>
                                            </a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}