ServiceHost/Areas/Store/Controllers/StoreMessageController.cs
using Framework.Application.Authentication;
using Framework.Peresentation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RadMarket.Query.Contracts.StoreTicketAgg;
using ReflectionIT.Mvc.Paging;
using ServiceHost.Tools;
using StoreManagement.Application.Contract.StoreAgg;
using System.Threading.Tasks;
using TicketManagement.Application.Contract.StoreTicketAgg;

namespace ServiceHost.Areas.Store.Controllers
{
    [StorePermissionChecker(SellerPermissionHelper.SendMessage)]
    public class StoreMessageController : StoreBaseController
    {
        private readonly IStoreTicketQuery _storeTicketQuery;
        private readonly IStoreApplication _storeApplication;
        private readonly IStoreTicketApplication _storeTicketApplication;

        public StoreMessageController(IStoreTicketQuery storeTicketQuery, IStoreApplication storeApplication, IStoreTicketApplication storeTicketApplication)
        {
            _storeTicketQuery = storeTicketQuery;
            _storeApplication = storeApplication;
            _storeTicketApplication = storeTicketApplication;
        }

        public async Task<IActionResult> Index(int pageIndex = 1)
        {
            var tickets = await _storeTicketQuery.GetAllBy(User.GetStoreId());

            var model = PagingList.Create(tickets, 10, pageIndex);

            ViewBag.Rows = (10 * pageIndex) - 9;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateStoreTicketVM command)
        {
            command.FirstStoreId = User.GetStoreId();
            if (ModelState.IsValid)
            {
                var result = await _storeTicketApplication.Create(command);

                if (result.IsSucceeded)
                {
                    TempData[SuccessMessage] = result.Message;
                    return RedirectToAction("Index");
                }

                TempData[ErrorMessage] = result.Message;
            }
            ViewBag.Stores = new SelectList(await _storeApplication.GetAll(), "Id", "Name");
            return View(command);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(long id)
        {
            var ticket = await _storeTicketQuery.GetBy(id, User.GetStoreId());

            if (ticket is null)
            {
                TempData[ErrorMessage] = "شما دسترسی به تیکت بقیه ندارید";
                return RedirectToAction("Index");
            }

            ViewBag.StoreId = User.GetStoreId();

            return View(ticket);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> SendMessage(AddStoreTicketMessageVM command)
        {
            command.SenderId = User.GetStoreId();

            if (ModelState.IsValid)
            {
                var result = await _storeTicketApplication.SendMessage(command);

                if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;
                else TempData[ErrorMessage] = result.Message;
            }

            return RedirectToAction("Detail", new { id = command.StoreTicketId, area = "Store" });
        }
    }
}

ServiceHost/Areas/Store/Views/StoreMessage/Create.cshtml
@model TicketManagement.Application.Contract.StoreTicketAgg.CreateStoreTicketVM
@{
    ViewData["Title"] = "ارسال پیام";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script src="https://cdn.tiny.cloud/1/bofsilxqs8ay4n0o4a3vj02ny82abzm5uryl93ih0pkmq2tm/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#TinyArea',
            plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            toolbar_mode: 'floating',
        });
    </script>
}

<div class="auth-user container col-sm-12 col md-8 col-lg-6">
    <div class="d-flex justify-content-center">
        <h4>فرم @ViewData["Title"]</h4>
    </div>
    <div class="auth">
        <form asp-controller="StoreMessage" asp-action="Create" method="post" class="p-3">

            <div class="row mb-3">
                <div class="col-6">
                    <label for="exampleInputEmail1" class="form-label">شرکت</label>
                    <select class="form-select" aria-label="Default select example" asp-for="SecondStoreId" asp-items="@ViewBag.Stores">
                        <option value="0">انتخاب کنید...</option>
                    </select>
                    <span asp-validation-for="SecondStoreId" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <label for="exampleInputPassword1" class="form-label">موضوع</label>
                    <input type="" asp-for="Title" class="form-control" id="exampleInputPassword1">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">دلیل</label>
                <textarea asp-for="Message" id="TinyArea" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-outline-danger w-50">ارسال</button>
            </div>
        </form>
    </div>
</div>

ServiceHost/Areas/Store/Views/StoreMessage/Detail.cshtml
@using TicketManagement.Application.Contract.StoreTicketAgg
@model RadMarket.Query.Contracts.StoreTicketAgg.StoreTicketQueryVM
@{
    ViewData["Title"] = "جزییات پیام";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script src="https://cdn.tiny.cloud/1/bofsilxqs8ay4n0o4a3vj02ny82abzm5uryl93ih0pkmq2tm/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#TinyArea',
            plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            toolbar_mode: 'floating',
        });
    </script>
}

@section Styles
{
    <link rel="stylesheet" href="~/css/ChatRoom.css" />
}

<div class="auth-user container col-sm-12 col md-8 col-lg-6">
    <div class="d-flex justify-content-center">
        <h4>فرم @ViewData["Title"]</h4>
    </div>
    <div class="auth">
        <partial name="_AnswerTicketPartial" model="@(new AddStoreTicketMessageVM{StoreTicketId = Model.Id})" />

        <hr />
        <ul class="messages" id="messages">
            @if (Model.Messages != null && Model.Messages.Any())
            {
                foreach (var message in Model.Messages)
                {
                    <li class="message @(message.SenderId == ViewBag.StoreId ? "right" : "left") appeared">
                        <div class="text_wrapper">
                            <div class="time">
                                @message.SentDate
                            </div>
                            <div class="text" style="font-size: 16px">
                                @Html.Raw(message.Message)
                            </div>
                        </div>
                    </li>
                }
            }
        </ul>
    </div>
</div>

ServiceHost/Areas/Store/Views/StoreMessage/Index.cshtml
@using Framework.Application
@model ReflectionIT.Mvc.Paging.PagingList<RadMarket.Query.Contracts.StoreTicketAgg.StoreTicketQueryVM>
@addTagHelper *, ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "لیست پیام ها";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- .create-box-me -->
<div class="container my-5">
    <div class="search-box-me">
        <i class="fa fa-plus text-dark"></i>
        <a asp-controller="StoreMessage" asp-action="Create">ارسال پیام</a>
    </div>
</div>
<!-- .create-box-me -->
<!-- tabels -->
<div class="table-me container my-5" style="overflow-y: scroll !important">
    @if (Model.Count == 0 || Model.Any() is false)
    {
        <p class="alert alert-warning"> هیچ پیامی وجود ندارد </p>
    }
    else
    {
        <table class="table table-striped table-hover" style="overflow-y: scroll;">
            <thead>
                <tr>
                    <th scope="col">شماره</th>
                    <th scope="col">موضوع</th>
                    <th scope="col">ارسالی از طرف</th>
                    <th scope="col">گیرنده پیام</th>
                    <th scope="col">تاریخ ایجاد</th>
                    <th scope="col">عملیات</th>

                </tr>
            </thead>


            <tbody>

                @foreach (var entity in Model)
                {
                    <tr>
                        <td scope="row"> @(ViewBag.Rows++)</td>
                        <td>@entity.Title</td>
                        <td>@entity.FirstStoreName</td>
                        <td>@entity.SecondStoreName</td>
                        <td>@entity.CreationDate</td>

                        <td><a asp-controller="StoreMessage" asp-action="Detail" asp-route-id="@entity.Id" class="btn-sm btn-primary">پیام ها</a></td>
                    </tr>
                }
            </tbody>

        </table>
    }

</div>
<!-- tabels -->
<!-- Paginate -->
@if (Model.PageCount > 1)
{
    <div class="my-5">
        <nav aria-label="Suppliers navigation example">
            <vc:pager paging-list="@Model" />
        </nav>
    </div>
}
<!-- Paginate -->