ServiceHost/Areas/Admin/Controllers/AdtPackageController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceHost.Tools;
using StoreManagement.Application.Contract.AdtPackageAgg;
using StoreManagement.Infrastructure.Configuration;
using System.Threading.Tasks;

namespace ServiceHost.Areas.Admin.Controllers
{
    [AdminPermissionChecker(StorePermissionHelper.AdtPackages)]
    public class AdtPackageController : AdminBaseController
    {
        private readonly IAdtPackageApplication _adtPackageApplication;

        public AdtPackageController(IAdtPackageApplication packageApplication) => _adtPackageApplication = packageApplication;

        public async Task<IActionResult> Index() => View(await _adtPackageApplication.GetAll());

        [HttpGet]
        public IActionResult Create() => PartialView();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAdtPackageVM command)
        {
            var result = await _adtPackageApplication.Create(command);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id) => PartialView(await _adtPackageApplication.GetDetailForEditBy(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditAdtPackageVM command)
        {
            var result = await _adtPackageApplication.Edit(command);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }

        [HttpGet]
        public IActionResult Delete(long id) => PartialView(id);

        [ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(long id)
        {
            var result = await _adtPackageApplication.Delete(id);

            if (result.IsSucceeded) TempData[SuccessMessage] = result.Message;

            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Store/Controllers/AdtPackageController.cs
using Framework.Application.Authentication;
using Framework.Peresentation;
using Microsoft.AspNetCore.Mvc;
using ServiceHost.Tools;
using StoreManagement.Application.Contract.AdtPackageAgg;
using StoreManagement.Application.Contract.StoreAgg;
using System.Threading.Tasks;

namespace ServiceHost.Areas.Store.Controllers
{
    [StorePermissionChecker(SellerPermissionHelper.AdtPackages)]
    public class AdtPackageController : StoreBaseController
    {
        private readonly IStoreApplication _storeApplication;
        private readonly IAdtPackageApplication _adtPackageApplication;

        public AdtPackageController(IStoreApplication storeApplication, IAdtPackageApplication adtPackageApplication)
        {
            _storeApplication = storeApplication;
            _adtPackageApplication = adtPackageApplication;
        }

        public async Task<IActionResult> Index()
        {
            var hasAdtCharge = await _storeApplication.IsAccountStillAdtCharged(User.GetStoreId());

            if (hasAdtCharge.IsSucceeded)
            {
                TempData[WarningMessage] = hasAdtCharge.Message;
                return RedirectToAction("Index", "Dashboard");
            }

            return View(await _adtPackageApplication.GetAll());
        }
    }
}

ServiceHost/Areas/Admin/Views/AdtPackage/Create.cshtml
@model StoreManagement.Application.Contract.AdtPackageAgg.CreateAdtPackageVM

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد پکیج تبلیغاتی جدید</h4>
</div>

<form asp-controller="AdtPackage" asp-action="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Type" class="control-label">نوع تبلیغ</label>
                    <select class="form-control" asp-for="Type">
                        <option value="0">بنر</option>
                        <option value="1">محصول</option>
                    </select>
                    <span asp-validation-for="Type" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Cost" class="control-label">قیمت</label>
                    <input type="number" min="0" class="form-control" asp-for="Cost">
                    <span asp-validation-for="Cost" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="ImageFile" accept="image/*">
                    <span asp-validation-for="ImageFile" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control" asp-for="Description"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/AdtPackage/Delete.cshtml
@model long

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">حذف</h4>
</div>

<form asp-area="Admin" asp-controller="AdtPackage" asp-action="Delete"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <h5 style="font-style: oblique">آیا از حذف این موجودیت اطمینان دارید؟</h5>
    </div>
    <div class="modal-footer">
        <input name="id" asp-for="@Model" type="hidden" />
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">خیر</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">بله</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/AdtPackage/Edit.cshtml
@model StoreManagement.Application.Contract.AdtPackageAgg.EditAdtPackageVM

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش پکیج تبلیغاتی</h4>
</div>

<form asp-controller="AdtPackage" asp-action="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Type" class="control-label">نوع تبلیغ</label>
                    <select class="form-control" asp-for="Type">
                        <option value="0">بنر</option>
                        <option value="1">محصول</option>
                    </select>
                    <span asp-validation-for="Type" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Cost" class="control-label">قیمت</label>
                    <input type="number" min="0" class="form-control" asp-for="Cost">
                    <span asp-validation-for="Cost" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="ImageFile" accept="image/*">
                    <span asp-validation-for="ImageFile" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control" asp-for="Description"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ImageName" />
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Views/AdtPackage/Index.cshtml
@model IEnumerable<StoreManagement.Application.Contract.AdtPackageAgg.AdtPackageVM>
@using Framework.Application
@{
    ViewData["Title"] = "پکیج های تبلیغاتی";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Action("Create", "AdtPackage")">ایجاد پکیج تبلیغاتی جدید</a>
        </p>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@ViewData["Title"]</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 makeTableResponsive">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>تصویر</th>
                                    <th>عنوان</th>
                                    <th>نوع</th>
                                    <th>قیمت(تومان)</th>
                                    <th>تعداد سفارش</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                @foreach (var entity in Model)
                                {
                                    <tr class="text-center">
                                        <td>@entity.Id</td>
                                        <td><img src="~/Pictures/@entity.ImageName" style="width: 85px; height: 85px; border-radius: 10px" /></td>
                                        <td>@entity.Title</td>
                                        <td>@entity.Type.GetEnumName()</td>
                                        <td>@entity.Cost.ToMoney()</td>
                                        <td>@entity.OrderCount</td>

                                        <td style="text-align: center;">

                                            <a class="btn btn-warning pull-right m-rl-5"
                                               href="#showmodal=@Url.Action("Edit", "AdtPackage", new {id = entity.Id})">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <a class="btn btn-danger pull-right m-rl-5"
                                               href="#showmodal=@Url.Action("Delete", "AdtPackage", new {id = entity.Id})">
                                                <i class="fa fa-trash"></i>
                                            </a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}